### ISSUE TITLE
Profile Enterprice

### ISSUE THREAD

**Issue by ManhND27** [THAO1999/SE04-Nhom27.1#11]

**Comment by ManhND27** [comment]
Interface on Enterprice có đồng bộ màu với giao diện giáo viên không nhỉ ?

**Comment by THAO1999** [comment]
không liên quan luôn

**Comment by THAO1999** [comment]
sửa nhanh lên bạn ơi

**Comment by ManhND27** [comment]
Có mấy cái element sẵn của theme ý . xóa đi  b ơi

**Comment by THAO1999** [comment]
m xóa luôn đi

**Comment by ManhND27** [comment]
done
