### ISSUE TITLE
Layout Student

### ISSUE THREAD

**Issue by vuq40255** [THAO1999/SE04-Nhom27.1#12]
![Capture](https://user-images.githubusercontent.com/69165998/99645976-7f9c5900-2a82-11eb-89c6-8fd951fe23f7.PNG)

**Comment by vuq40255** [comment]
![InkedCapture_LI](https://user-images.githubusercontent.com/69165998/99646173-be321380-2a82-11eb-892b-3df982b74655.jpg)

Tiều đề này nên thay như thế nào nhỉ?

**Comment by vuq40255** [comment]
![InkedCapture_LI](https://user-images.githubusercontent.com/69165998/99870991-bf417d00-2c09-11eb-9a01-de3bccb8b8c5.jpg)

ae xem cả logo này ổn chưa

**Comment by THAO1999** [comment]
ý nghĩa của logo ấy là gì?

**Comment by vuq40255** [comment]
Để logo cũ cũng được
