### ISSUE TITLE
Header-Student

### ISSUE THREAD

**Issue by vuq40255** [THAO1999/SE04-Nhom27.1#13]
![Capture1](https://user-images.githubusercontent.com/69165998/99874138-ebfc9100-2c17-11eb-98fa-8595999b9131.PNG)

Trong menu sinhvien2 có "My Account" và "My Job Robot" ở file giống nhau

**Comment by THAO1999** [comment]
ơ, thế thì chưa được cập nhật rồi

**Comment by THAO1999** [comment]
thử click tìm kiếm theo tên công ty xem nút đấy đã được cập nhật chưa

**Comment by vuq40255** [comment]
Cập nhật ok rồi nhé
