### ISSUE TITLE
Layout teacher

### ISSUE THREAD

**Issue by Assyrian2234** [THAO1999/SE04-Nhom27.1#14]

**Comment by Assyrian2234** [comment]
![image](https://user-images.githubusercontent.com/69194753/100703932-27951900-33d7-11eb-93e9-b93aa62124b0.png)

**Comment by Assyrian2234** [comment]
ek chỗ này làm gì đây

**Comment by THAO1999** [comment]
login vào sẽ hiện lên Giao diện Chờ Giáo viên xác nhận phiếu

**Comment by THAO1999** [comment]
Bỏ giao diện kia đi cũng dc

**Comment by Assyrian2234** [comment]
ok

**Comment by Assyrian2234** [comment]
![image](https://user-images.githubusercontent.com/69194753/101244576-e899f700-3739-11eb-818e-53156f90322c.png)

**Comment by Assyrian2234** [comment]
cái chỗ quản lí phiếu nhìn hơi đơn giản thì phải

**Comment by Assyrian2234** [comment]
![image](https://user-images.githubusercontent.com/69194753/101244593-04050200-373a-11eb-92e4-a6313f81b88d.png)

**Comment by Assyrian2234** [comment]
chỗ này mà ko có phiếu nào nhìn ko ổn lắm

**Comment by THAO1999** [comment]
> chỗ này mà ko có phiếu nào nhìn ko ổn lắm

tại chưa có phiếu nào thì hiện như vậy. giờ m nghĩ xem có câu nào hợp lí cho phần đấy k

**Comment by Assyrian2234** [comment]
chưa có phiếu nào thì xóa chữ đi dc ko

**Comment by Assyrian2234** [comment]
hoặc để hiện kiểu tất cả phiếu đã dc xác nhận

**Comment by THAO1999** [comment]
thế thì chuyển link đến phiếu đã xác nhận cũng dc

**Comment by Assyrian2234** [comment]
để thử xem
