### ISSUE TITLE
Detail Student

### ISSUE THREAD

**Issue by vuq40255** [THAO1999/SE04-Nhom27.1#15]
![Capture](https://user-images.githubusercontent.com/69165998/100616432-ad6b8280-334b-11eb-9ef1-5e5508d8746b.PNG)

Cần thêm Icon phía trước các thông tin

**Comment by THAO1999** [comment]
nếu thêm dc thì cứ thêm nha

**Comment by THAO1999** [comment]
bỏ "Trạng thái:Trong thời gian đăng kí đi" ... cái này k cần thiết, vì đã có hạn đăng kí rôi

**Comment by vuq40255** [comment]
![Capture](https://user-images.githubusercontent.com/69165998/101296080-05c2e880-3854-11eb-8ac7-28f9450ec8f9.PNG)

Sửa xong r nhé

**Comment by THAO1999** [comment]
tạo pull request đi, t review

**Comment by vuq40255** [comment]
Tạo rồi đó, vào review đi

**Comment by THAO1999** [comment]
done
