### ISSUE TITLE
Home Enterprice

### ISSUE THREAD

**Issue by ManhND27** [THAO1999/SE04-Nhom27.1#17]
![image](https://user-images.githubusercontent.com/57554972/101449484-76a0f800-395b-11eb-9f48-f24bef4cec9f.png)
màu này ko thấy chữ t sửa thành màu khác nhé

**Comment by THAO1999** [comment]
sửa đi, ưng mắt là đc

**Comment by ManhND27** [comment]
Delete footer roi day

**Comment by THAO1999** [comment]
chụp ảnh lên

**Comment by THAO1999** [comment]
xong rồi thì tạo pull request

**Comment by ManhND27** [comment]
done
