### ISSUE TITLE
Profile-Student

### ISSUE THREAD

**Issue by vuq40255** [THAO1999/SE04-Nhom27.1#18]
![Capture](https://user-images.githubusercontent.com/69165998/101502775-efc43d80-39a3-11eb-9903-67be4a9ac9db.PNG)

Trang này cần thêm chút màu mè với khung cho bớt trống trải nhỉ

**Comment by vuq40255** [comment]
@THAO1999 nút Home có cần thiết không hay bỏ đi?

**Comment by THAO1999** [comment]
cứ để tạm Home ở đó

**Comment by THAO1999** [comment]
thay đổi all tiếng anh thành tiếng việt đi

**Comment by THAO1999** [comment]
![image](https://user-images.githubusercontent.com/48828095/101505132-98739c80-39a6-11eb-82ca-3d57ada307f9.png)

sửa tên tiếng việt ở đây: backend/models/Student;
ví dụ   'username' => 'Username', thì sẽ sưa là   'username' => 'Tên Sinh Viên',
chỗ khác sửa tương tự

**Comment by THAO1999** [comment]
![image](https://user-images.githubusercontent.com/48828095/101506358-df15c680-39a7-11eb-9247-83bcf0772390.png)
sửa lại màn Home :uy tín...... 
chữ cái đầu viết hoa :Uy Tín - Trách Nhiệm

**Comment by vuq40255** [comment]
![Capture](https://user-images.githubusercontent.com/69165998/101509587-80eae280-39ab-11eb-965e-6856b4acde03.PNG)
 ok

**Comment by vuq40255** [comment]
![Capture1](https://user-images.githubusercontent.com/69165998/101509945-e5a63d00-39ab-11eb-8118-644454dfbdea.PNG)
rồi này

**Comment by THAO1999** [comment]
chay lên xem có cần sửa gì nữa k

**Comment by vuq40255** [comment]
Sao t k sửa style của css trong trang ProfileStudent nhỉ? @THAO1999

**Comment by THAO1999** [comment]
muốn sửa cái gì , chụp ảnh lên đây t xem
