### ISSUE TITLE
Edit CreateEnterprice

### ISSUE THREAD

**Issue by ManhND27** [THAO1999/SE04-Nhom27.1#19]

**Comment by ManhND27** [comment]
vào check xem có thêm gì không nhé

**Comment by THAO1999** [comment]
gửi giao diện lên đây

**Comment by ManhND27** [comment]
![image](https://user-images.githubusercontent.com/57554972/102153376-a72be900-3ea9-11eb-8c87-f2c63a5a955d.png)
day nay co chinh sua gi ko  🔢
