### ISSUE TITLE
Design Diagram and Database

### ISSUE THREAD

**Issue by ManhND27** [THAO1999/SE04-Nhom27.1#2]
Sơ qua thì Project gồm có 3 class chính là giáo viên, sinh viên thực tập và doanh nghiệp . 
- Giáo viên thì gồm có các thuộc tính cơ bản là :
 +Tên giáo viên
 +Chủ bộ môn 
- Sinh viên : 
 +Tên sinh viên 
 + Những môn đã pass
 + Điểm mạnh 
 + Điểm yếu 
 + Mong muốn lĩnh vực thực tập
- Doanh nghiệp :
 + Lĩnh vực tuyển dụng 
 + Yêu cầu tuyển dụng  
Thiếu gì thì anh em bổ sung với :3

**Comment by ManhND27** [comment]
Commit Design Diagram vào trong mục Design à

**Comment by ManhND27** [comment]
Project này sinh ra để kết nối giữa sinh viên nhà trường và doanh nghiệp thì là sinh viên vào web lựa chọn doanh nghiệp và doanh nghiệp vào trang quản trị lựa chọn sinh viên hay yêu phân sinh viên thực tập là của giáo viên ?

**Comment by ManhND27** [comment]
thầy thiết kế Diagram bằng phầm mềm gì nhỉ

**Comment by THAO1999** [comment]
đây https://app.diagrams.net/

**Comment by THAO1999** [comment]
> Project này sinh ra để kết nối giữa sinh viên nhà trường và doanh nghiệp thì là sinh viên vào web lựa chọn doanh nghiệp và doanh nghiệp vào trang quản trị lựa chọn sinh viên hay yêu phân sinh viên thực tập là của giáo viên ?

**Comment by THAO1999** [comment]
> Commit Design Diagram vào trong mục Design à

**Comment by vuq40255** [comment]
Doanh nghiệp đâu có lựa chọn sinh viên được mà sinh viên đăng ký nguyện vọng rồi giáo viên dựa trên nguyện vọng đó để sắp xếp thực tập :3

> Project này sinh ra để kết nối giữa sinh viên nhà trường và doanh nghiệp thì là sinh viên vào web lựa chọn doanh nghiệp và doanh nghiệp vào trang quản trị lựa chọn sinh viên hay yêu phân sinh viên thực tập là của giáo viên ?

**Comment by ManhND27** [comment]
Thế thì sinh viên vào web lựa chọn doanh nghiệp rồi giáo viên có dữ liệu trước rồi mới phân cho doanh nghiệp à 

> Doanh nghiệp đâu có lựa chọn sinh viên được mà sinh viên đăng ký nguyện vọng rồi giáo viên dựa trên nguyện vọng đó để sắp xếp thực tập :3
> 
> > Project này sinh ra để kết nối giữa sinh viên nhà trường và doanh nghiệp thì là sinh viên vào web lựa chọn doanh nghiệp và doanh nghiệp vào trang quản trị lựa chọn sinh viên hay yêu phân sinh viên thực tập là của giáo viên ?
