### ISSUE TITLE
Edit version 2 display Enterprice

### ISSUE THREAD

**Issue by ManhND27** [THAO1999/SE04-Nhom27.1#23]
check lai cac man 1 lan di @THAO1999

**Comment by THAO1999** [comment]
sửa xong hết chưa

**Comment by ManhND27** [comment]
sửa theo yêu cầu của m lần trước rồi đấy vào check xem còn gì sửa phát nữa

**Comment by THAO1999** [comment]
chú ý cách đặt tên issue

**Comment by ManhND27** [comment]
rename roi 👍

**Comment by THAO1999** [comment]
issue kia có ý nghĩa gì?
xem lại rule issue

**Comment by ManhND27** [comment]
chỉ sửa giao diện doanh nghiệp lần 2 :V
