### ISSUE TITLE
Giao diện sinh viên

### ISSUE THREAD

**Issue by vuq40255** [THAO1999/SE04-Nhom27.1#3]
Phần header của trang nên để những nội dung nào?

**Comment by THAO1999** [comment]
dropdown-menu, button logout

**Comment by vuq40255** [comment]
![Capture](https://user-images.githubusercontent.com/69165998/96224775-4d4a9800-0fba-11eb-9ccb-bbe33cb9c670.PNG)
Icon của đánh giá sao bị lỗi rồi, trong khi các icon khác vẫn hiện lên đúng. Ae sửa giúp với

**Comment by THAO1999** [comment]
ở OrganizationRequest_detail , thay button viết review thành đăng kí

**Comment by THAO1999** [comment]
Bỏ button theo dõi, nêu   k fix  dc icon thì thay icon khác

**Comment by THAO1999** [comment]
> ![Capture](https://user-images.githubusercontent.com/69165998/96224775-4d4a9800-0fba-11eb-9ccb-bbe33cb9c670.PNG)
> Icon của đánh giá sao bị lỗi rồi, trong khi các icon khác vẫn hiện lên đúng. Ae sửa giúp với

dùng tool check file gốc, xem icon đấy ở chỗ nào, xem tương đồng file này k

**Comment by vuq40255** [comment]
Thay mục tổng quát bằng Review ở phía dưới được k? Vì việc dánh giá sao này là động chứ kp tĩnh
