### ISSUE TITLE
Giao diện Đăng nhập Sinh Viên

### ISSUE THREAD

**Issue by vuq40255** [THAO1999/SE04-Nhom27.1#6]

**Comment by vuq40255** [comment]
Có cần thêm nút đăng ký k?

**Comment by THAO1999** [comment]
hông, vi giáo viên sẽ tạo

**Comment by vuq40255** [comment]
oke.
Có thêm yc Forgot user/password trong gd khi sv quên mật khẩu hay tên đăng nhập k?

**Comment by THAO1999** [comment]
có, nhưng hiện tại chưa làm chức năng ấy

**Comment by vuq40255** [comment]
![Capture](https://user-images.githubusercontent.com/69165998/97945852-552c7980-1dbb-11eb-8e8f-5bf891a6cf8c.PNG)

Giao diện Login ok chưa?

**Comment by THAO1999** [comment]
ok
