### ISSUE TITLE
Giao diện đăng nhập giáo viên

### ISSUE THREAD

**Issue by Assyrian2234** [THAO1999/SE04-Nhom27.1#7]

**Comment by Assyrian2234** [comment]
Có cần thêm nút "nhớ tài khoản" ko

**Comment by THAO1999** [comment]
tạm thời cứ thêm vào, nhưng chưa làm chức năng đấy

**Comment by THAO1999** [comment]
gửi giao diện lên đây t xem

**Comment by Assyrian2234** [comment]
đây xem cần thêm gì
![125487358_1708503075980480_2295793085756941063_n](https://user-images.githubusercontent.com/69194753/99645566-f84ee580-2a81-11eb-8706-4fb581c3d285.png)

**Comment by THAO1999** [comment]
ok
